version: '3.8'

services:
  portfolio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=https://capybara.cx.ua
    volumes:
      - ./feedbacks.sqlite:/app/feedbacks.sqlite
