export { GithubIcon } from './GithubIcon'
export { GmailIcon } from './GmailIcon'
export { LinkedInIcon } from './LinkedInIcon'
export { MonkeytypeIcon } from './MonkeytypeIcon'
export type { IconProps } from './types'
export { WakatimeIcon } from './WakatimeIcon'
